{{- $fullName := include "cron-backup.fullname" . -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "cron-backup.fullname" . }}
  labels:
    {{ include "cron-backup.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.backup.schedule | quote }}
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: {{ .Values.backup.startingDeadlineSeconds }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.backup.backoffLimit }}
      activeDeadlineSeconds: {{ .Values.backup.activeDeadlineSeconds }}
      parallelism: 1
      completions: 1
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          {{- range $key, $value := .Values.containers }}
          - name: {{ $value.name }}
            image: {{ $value.image.repository }}:{{ $value.image.tag }}
            imagePullPolicy: {{ $value.image.pullPolicy }}
            command: ["/scripts/{{ $value.name }}.sh"]
            env:
            {{- range $envKey, $envValue := $value.extraEnvironmentVars }}
            - name: {{ $envKey }}
              value: {{ $envValue }}
            {{- end }}
            {{- range $envKey, $envValue := $value.extraSecretEnvironmentVars }}
            - name: {{ $envKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-{{ $key }}
                  key: {{ $envKey }}
            {{- end }}
            resources:
              {{- toYaml $value.resources | nindent 14 }}
            volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: backups
              mountPath: /backups
          {{- end }}
          volumes:
            - name: scripts
              configMap:
                name: {{ include "cron-backup.fullname" . }}
                defaultMode: 0777
            - name: backups
              emptyDir: {}
