{{- range $key, $value := .Values.containers }}
{{- if gt (len $value.extraSecretEnvironmentVars) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cron-backup.fullname" . }}-{{ $key }}
  labels:
    {{ include "cron-backup.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $secretKey, $secretValue := $value.extraSecretEnvironmentVars }}
  {{ $secretKey }} : {{ $secretValue | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
