{{- $root := . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cron-backup.fullname" . }}
  labels:
    {{ include "cron-backup.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.containers }}
  {{ $value.name }}.sh: |
    {{- tpl $value.script $root | nindent 4 }}
  {{- end }}